blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/Ghenwy/claude-code-toolkit/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 📚 Documentation
    url: https://github.com/Ghenwy/claude-code-toolkit#-documentation
    about: Check our comprehensive guides and API reference
  - name: ⚡ Quick Start Guide
    url: https://github.com/Ghenwy/claude-code-toolkit#-quick-start-30-seconds
    about: Get up and running in 30 seconds